server:
  port: 8085
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 199875
    url: jdbc:mysql://localhost:3306/pink?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小


mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
  type-aliases-package: com.work.pinkweb.Entity